#!/usr/bin/env bash
# dev.sh — Start dev environment with isolated ports.
#
# Each checkout gets its own Docker containers (via COMPOSE_PROJECT_NAME)
# and dynamically assigned ports, so multiple checkouts can run concurrently.
#
# Usage:
#   ./dev.sh          # Start ClickHouse + Next.js
#   ./dev.sh infra    # Start ClickHouse only
#   ./dev.sh app      # Start Next.js only (assumes ClickHouse is running)
#   ./dev.sh down     # Stop containers
#   ./dev.sh ports    # Show assigned ports
set -euo pipefail

ENV_FILE=".env.local"
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_NAME="crt-$(basename "$PROJECT_DIR" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')"

export COMPOSE_PROJECT_NAME="$PROJECT_NAME"

# --- Port management ---

find_free_port() {
  python3 -c 'import socket; s=socket.socket(); s.bind(("",0)); print(s.getsockname()[1]); s.close()'
}

# Write .env.local with ports (only if not already set for this session)
ensure_ports() {
  if [[ -f "$ENV_FILE" ]] && grep -q "^CLICKHOUSE_HTTP_PORT=" "$ENV_FILE" 2>/dev/null; then
    # Reuse existing ports
    source "$ENV_FILE"
  else
    CLICKHOUSE_HTTP_PORT=$(find_free_port)
    CLICKHOUSE_NATIVE_PORT=$(find_free_port)
    NEXT_PORT=$(find_free_port)

    cat > "$ENV_FILE" <<EOF
# Auto-generated by dev.sh — do not commit
CLICKHOUSE_HTTP_PORT=$CLICKHOUSE_HTTP_PORT
CLICKHOUSE_NATIVE_PORT=$CLICKHOUSE_NATIVE_PORT
CLICKHOUSE_URL=http://localhost:$CLICKHOUSE_HTTP_PORT
CLICKHOUSE_USER=default
CLICKHOUSE_PASSWORD=dev
CLICKHOUSE_DB=code_review_trends
NEXT_PORT=$NEXT_PORT
EOF
    echo "Generated $ENV_FILE with dynamic ports"
  fi

  export CLICKHOUSE_HTTP_PORT CLICKHOUSE_NATIVE_PORT CLICKHOUSE_URL CLICKHOUSE_USER CLICKHOUSE_PASSWORD CLICKHOUSE_DB NEXT_PORT
  CLICKHOUSE_URL="http://localhost:$CLICKHOUSE_HTTP_PORT"
  export CLICKHOUSE_URL
}

print_ports() {
  echo ""
  echo "  Project:        $PROJECT_NAME"
  echo "  ClickHouse HTTP: http://localhost:$CLICKHOUSE_HTTP_PORT"
  echo "  ClickHouse TCP:  localhost:$CLICKHOUSE_NATIVE_PORT"
  echo "  Next.js:         http://localhost:$NEXT_PORT"
  echo ""
}

# --- Commands ---

start_infra() {
  ensure_ports
  echo "Starting ClickHouse..."
  docker compose up -d
  print_ports
}

start_app() {
  ensure_ports
  print_ports
  echo "Starting Next.js on port $NEXT_PORT..."
  cd app && npx next dev --port "$NEXT_PORT"
}

stop() {
  if [[ -f "$ENV_FILE" ]]; then
    source "$ENV_FILE"
  fi
  docker compose down
  echo "Containers stopped."
}

show_ports() {
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "No $ENV_FILE found. Run ./dev.sh first."
    exit 1
  fi
  source "$ENV_FILE"
  print_ports
}

# --- Main ---

case "${1:-all}" in
  all)
    start_infra
    start_app
    ;;
  infra)
    start_infra
    ;;
  app)
    start_app
    ;;
  down|stop)
    stop
    ;;
  ports)
    show_ports
    ;;
  *)
    echo "Usage: ./dev.sh [all|infra|app|down|ports]"
    exit 1
    ;;
esac
