config:
  gcp:region: us-central1
  gcp:zone: us-central1-a
  code-review-trends:environment: staging
  code-review-trends:clickhouseMachineType: e2-highmem-2
  code-review-trends:clickhouseDiskSizeGb: "40"
  code-review-trends:appMemory: "4Gi"
  code-review-trends:appCpu: "2"
  code-review-trends:appMinInstances: "1"
  code-review-trends:appMaxInstances: "10"
  code-review-trends:appConcurrency: "40"
  gcp:project:
    secure: v1:pPeFMdNeIwwNUtMk:ZBEWf3Wc4tu/V8VTkVtbQLL9kAQxTnsy7f5OiQ==
  code-review-trends:artifactRegistryLocation: us-central1
  code-review-trends:clickhousePublicAccess: "true"
  code-review-trends:githubRepo: bruno-garcia/code-review-trends
  code-review-trends:clickhouseDomain:
    secure: v1:WtI0hDYGsugbuqPR:beB4SPLLDn9yw1pLMb+9mZRUqlc/wf91ZWmAZce6VM88K8qhuP0=
  code-review-trends:appDomain:
    secure: v1:Cl9tlY9PoPO32Ntm:5JFf8PrN6xLThPSY27xcmScuYzFWaWAtwCNZkGqnryORDQ+tnJvmKjrC8CE=
  code-review-trends:sentryDsnPipeline:
    secure: v1:cpTzqMk64Wi0+6VJ:fPOBuT+6g7F5injRRtQLjpHD0+qiZEWi/OXCme1oDAplQIiF3ngltbmOnYOpVj8lhAAifI9D+yMJMPy71kwRyB2QUeMzCpU5lpy15m6qMFKza4U2xDKBhUFqTI2Mpxqiq3jkpiI=
  code-review-trends:sentryAuthToken:
    secure: v1:Hch9thv+iLMXVBnA:BjTyJ6n2uq5DU1EQFHvce7RRZNTiYcRz5muA7PujNEDQ2M1cz/3bPSC7RL1qkYl8xu9vsGqiwnPT2Vch9y0DAreH86ntnDzpjTd2i9HuR5kgTlLVPZ4gdnaI3W4WY5Sl2A+S8Ej06zCMdR+gvCZqVfnRCdZALkUSe8nJnS2INL2sLsGtiugjmLe7qGl6P/QJOGfwfwkeIfTrJVxjZr8bzcJxZciDRG2zg8JjEXzCwMwfJ9WiaXzAIyj4fdcuwynk9mgpZ4+qOc1zXnXErZX6R2oFbg==
  code-review-trends:sentryDsnAppFrontend:
    secure: v1:PhsUUN68nA8l9BXC:mWfknc7e+dCZ7KoW0S4QNLJ84EnozFOKnkY+72a35lpwcm/w4J/Y4nYXcRBZXQKARokPvScLSpLV4WXIXRwr8dzCaKQ1IzDCKqb9J0W9lIub7+3ZtduvTEVBYrpKCEqNfVVu3us=
  code-review-trends:sentryDsnAppBackend:
    secure: v1:MKS6H6fY1LXav1fr:LstnaeR3roDbxzvqgdtiPvXw+JEvEwnZzJxAfXnyBk8d96uJb+RzML8VaSkeZ5Kw1NubrquBF8wi3Oz7qS2swfTHB3ewYyoQ1gGKROkmjttIOXbWDSg9b54PQCIGMscotO9nENM=
  code-review-trends:alertEmail:
    secure: v1:Bfh6iTwwF69gV629:Q0e96DLmnVNqXfVWqoo+1Wlu7efCfTiDcl0wd6Di0kawySPmNwc8IHID
  code-review-trends:githubTokenCount: "4"
  code-review-trends:githubTokens:
    secure: v1:Zl24Eut3XHnxixgx:9SwyxEDgBypmzfTB8O5y5AtMPl3TPApUq5z3A9oXsg2kdN9DJv3UuG+QUE55C+MaLmpReehmkqkhfwkgmuEIqWfUxfIUCB5vv3UV6Duyl1X5rD6czJCEDoC19GhOrJBt0Qgx8/7CDMq+ErfK2ZKsKN9RliXN8Y+DML83/yKjXEizXDcoHZkXcggrdEsRgsy39oTYRA6cxg25PW8jIz/TTwWhgaIMpd2WmGuqnjnWEY0G4qcTwLb0KBjCWZK6gBU2sxBsXV1EWO+bVi6pzWKu5u15kxc3e0C73vyFrABV1tcSydruoHOqK+G7Z9DNQvqd/SleybOQKv1I6/1u/IuMR/ZR+QDT/SawtMZlxUCoY+OwzOA4H9mp7PZG2HnAxVxLZgVPITzG9KqemBbzVugYx3nicXK8Efu2qwLhRTDbMol0RmlUgLaLwfFi2YVHpgr71PseAaIaT1WEYQpx/zRX0Ru2jUeNsi/GNaUlngD6ak0+7aD21W8Gy25W01ekZrf6txMkGGNKFTmQKY24eokUE4szzvs=
encryptionsalt: v1:AWXWIyh26VY=:v1:Sg6zEq4QvISI5kjW:A7aV13N9kenv/uY9U3IQYM+qiSZTYg==
