config:
  gcp:region: us-central1
  gcp:zone: us-central1-a
  code-review-trends:environment: staging
  code-review-trends:clickhouseMachineType: e2-highmem-2
  code-review-trends:clickhouseDiskSizeGb: "40"
  code-review-trends:appMemory: "4Gi"
  code-review-trends:appCpu: "2"
  code-review-trends:appMinInstances: "1"
  code-review-trends:appMaxInstances: "10"
  code-review-trends:appConcurrency: "40"
  gcp:project:
    secure: v1:pPeFMdNeIwwNUtMk:ZBEWf3Wc4tu/V8VTkVtbQLL9kAQxTnsy7f5OiQ==
  code-review-trends:artifactRegistryLocation: us-central1
  code-review-trends:clickhousePublicAccess: "true"
  code-review-trends:githubRepo: bruno-garcia/code-review-trends
  code-review-trends:clickhouseDomain:
    secure: v1:WtI0hDYGsugbuqPR:beB4SPLLDn9yw1pLMb+9mZRUqlc/wf91ZWmAZce6VM88K8qhuP0=
  code-review-trends:appDomain:
    secure: v1:Cl9tlY9PoPO32Ntm:5JFf8PrN6xLThPSY27xcmScuYzFWaWAtwCNZkGqnryORDQ+tnJvmKjrC8CE=
  code-review-trends:sentryDsnPipeline:
    secure: v1:cpTzqMk64Wi0+6VJ:fPOBuT+6g7F5injRRtQLjpHD0+qiZEWi/OXCme1oDAplQIiF3ngltbmOnYOpVj8lhAAifI9D+yMJMPy71kwRyB2QUeMzCpU5lpy15m6qMFKza4U2xDKBhUFqTI2Mpxqiq3jkpiI=
  code-review-trends:sentryAuthToken:
    secure: v1:Hch9thv+iLMXVBnA:BjTyJ6n2uq5DU1EQFHvce7RRZNTiYcRz5muA7PujNEDQ2M1cz/3bPSC7RL1qkYl8xu9vsGqiwnPT2Vch9y0DAreH86ntnDzpjTd2i9HuR5kgTlLVPZ4gdnaI3W4WY5Sl2A+S8Ej06zCMdR+gvCZqVfnRCdZALkUSe8nJnS2INL2sLsGtiugjmLe7qGl6P/QJOGfwfwkeIfTrJVxjZr8bzcJxZciDRG2zg8JjEXzCwMwfJ9WiaXzAIyj4fdcuwynk9mgpZ4+qOc1zXnXErZX6R2oFbg==
  code-review-trends:sentryDsnAppFrontend:
    secure: v1:PhsUUN68nA8l9BXC:mWfknc7e+dCZ7KoW0S4QNLJ84EnozFOKnkY+72a35lpwcm/w4J/Y4nYXcRBZXQKARokPvScLSpLV4WXIXRwr8dzCaKQ1IzDCKqb9J0W9lIub7+3ZtduvTEVBYrpKCEqNfVVu3us=
  code-review-trends:sentryDsnAppBackend:
    secure: v1:MKS6H6fY1LXav1fr:LstnaeR3roDbxzvqgdtiPvXw+JEvEwnZzJxAfXnyBk8d96uJb+RzML8VaSkeZ5Kw1NubrquBF8wi3Oz7qS2swfTHB3ewYyoQ1gGKROkmjttIOXbWDSg9b54PQCIGMscotO9nENM=
  code-review-trends:alertEmail:
    secure: v1:Bfh6iTwwF69gV629:Q0e96DLmnVNqXfVWqoo+1Wlu7efCfTiDcl0wd6Di0kawySPmNwc8IHID
  code-review-trends:githubTokens:
    secure: v1:IScluHx/myptGCp6:BG4Di9KDSKJJDql45MOh+dIeb0QiWIk4utUvpz2MUL/CkYN6Prh3Jh9Tl9FnunbAffUq5fb5xPsKtp4IdkePkAUGdGn6prISjH44SzP/WsBW7u0xgUSPAoWxxR8XIj4sxcvele6YfsT7asVe9Ln+hMDrJ2/+R2jUM3qSM8x7zRJY/lDR3aRamCO586/Y+uaYZybEHgWxa0dbfHsahm4Cd3DnKWJz3ZIgt/32JQZwa3wAKkn5T2y3RH87uw/1pow7wDgrwQCq6iYI9n6giE8EPpchfijTXsMyuqy6JFCOhkP4EcSbHVwyW7FIy8Boo9mDzHevBpr07Kw6apGqSdTmbnXqpyiNAbkPmiFMxUOhrAt+3u9iMrCT2PcnK0B4v67T/c0RuMWZvXuJ4xZ9iN5TBErKa3vithT9K3GC0T6jEkMblBV733j3kwI8iYV5eC1Fb5CTcJP+PcAt/8Y+Bu3LJjhu07/OlWaFgIEKE8ZmjcYvFtVAp/Xda2YTsMgVo7NGWPXmSEylu94tKLjzNzQrGFFjQwKo03YYXwayrgZuPIpFBOusv4hrFpf81Vzer8jbuplMj9kL0zAwswKoQFGqoX9b+PzTvH4p76UAOGTyPP+lQEGdg8/LbCkzqQy80JdloiF+zQ8UMLkJ7MPPQn+pE9/TxEJvdlf2wl89mmgz5EiQ5Rr2RH3Am+sBEbcPyEY2sycCD6Rk0ta43FQooelNEAlJT/6RdWIZHRU1eT9BP2fbWqPrUfJld+IXRNY6/WKKqfxjpaL6YJTNnu24JjRJUqqzfrusLn/UHk8gAQO9PTBuyWG92Gz0oU+JsRg3CdSevudEoHcPM02lIsxTyhsbMZkSHsrQjOZeIQISqzgV9fs64s3xl86FXPF2sHW/LOmbzxCJo2BH911gXVGFWY+fH9LocIpazrQ=
  code-review-trends:workerProxyCount: "3"
  code-review-trends:workerSubnet:
    secure: v1:Dqo//9Hy93pb9WHl:n7a41x1etgOpMdlqb7cSHyBGchm0ddBkgyej8Xzfj6fI2Jb98BxPrT1PV4B4bWmEuUNqBe3qSS7AVSNX7tX8dznonkIzLByxFGfz7utuu8Q5XCT+w8wgokBrQcz/Zw==
  code-review-trends:workerVpcNetwork:
    secure: v1:ErysDS4Uj/0aR+2w:C1v+C/ejwo0bGzj/H2ypQ0kDPH4cPXwgj4c/SNQcp15SP9AkNuGqbrBxVQA7xi0kC/bO4AvGSqL6Evy1tRyoAhCb7ctMqlXrmziF
encryptionsalt: v1:AWXWIyh26VY=:v1:Sg6zEq4QvISI5kjW:A7aV13N9kenv/uY9U3IQYM+qiSZTYg==
