config:
  gcp:region: us-central1
  gcp:zone: us-central1-a
  code-review-trends:environment: staging
  code-review-trends:clickhouseMachineType: e2-highmem-2
  code-review-trends:clickhouseDiskSizeGb: "20"
  code-review-trends:appMemory: "4Gi"
  code-review-trends:appCpu: "2"
  code-review-trends:appMinInstances: "1"
  code-review-trends:appMaxInstances: "10"
  code-review-trends:appConcurrency: "40"
  gcp:project:
    secure: v1:pPeFMdNeIwwNUtMk:ZBEWf3Wc4tu/V8VTkVtbQLL9kAQxTnsy7f5OiQ==
  code-review-trends:artifactRegistryLocation: us-central1
  code-review-trends:clickhousePublicAccess: "true"
  code-review-trends:githubRepo: bruno-garcia/code-review-trends
  code-review-trends:clickhouseDomain:
    secure: v1:WtI0hDYGsugbuqPR:beB4SPLLDn9yw1pLMb+9mZRUqlc/wf91ZWmAZce6VM88K8qhuP0=
  code-review-trends:appDomain:
    secure: v1:Cl9tlY9PoPO32Ntm:5JFf8PrN6xLThPSY27xcmScuYzFWaWAtwCNZkGqnryORDQ+tnJvmKjrC8CE=
  code-review-trends:sentryDsnPipeline:
    secure: v1:cpTzqMk64Wi0+6VJ:fPOBuT+6g7F5injRRtQLjpHD0+qiZEWi/OXCme1oDAplQIiF3ngltbmOnYOpVj8lhAAifI9D+yMJMPy71kwRyB2QUeMzCpU5lpy15m6qMFKza4U2xDKBhUFqTI2Mpxqiq3jkpiI=
  code-review-trends:sentryAuthToken:
    secure: v1:Hch9thv+iLMXVBnA:BjTyJ6n2uq5DU1EQFHvce7RRZNTiYcRz5muA7PujNEDQ2M1cz/3bPSC7RL1qkYl8xu9vsGqiwnPT2Vch9y0DAreH86ntnDzpjTd2i9HuR5kgTlLVPZ4gdnaI3W4WY5Sl2A+S8Ej06zCMdR+gvCZqVfnRCdZALkUSe8nJnS2INL2sLsGtiugjmLe7qGl6P/QJOGfwfwkeIfTrJVxjZr8bzcJxZciDRG2zg8JjEXzCwMwfJ9WiaXzAIyj4fdcuwynk9mgpZ4+qOc1zXnXErZX6R2oFbg==
  code-review-trends:githubToken:
    secure: v1:/07hATRgDE91919j:ni7e5xV/uBRJdhONkk8Q6ixh9EExqODPeyzytk9A+OcDhOOR+mDR0FRQDz7MiH4xPkxlhCEAMfALatm0XwslforFZ6d9LbI5QgV3dhD2BYGqwy3YShdlQ+3kIpW7gmvk6TPosvWMI3Ry38Ak9A==
  code-review-trends:sentryDsnAppFrontend:
    secure: v1:PhsUUN68nA8l9BXC:mWfknc7e+dCZ7KoW0S4QNLJ84EnozFOKnkY+72a35lpwcm/w4J/Y4nYXcRBZXQKARokPvScLSpLV4WXIXRwr8dzCaKQ1IzDCKqb9J0W9lIub7+3ZtduvTEVBYrpKCEqNfVVu3us=
  code-review-trends:sentryDsnAppBackend:
    secure: v1:MKS6H6fY1LXav1fr:LstnaeR3roDbxzvqgdtiPvXw+JEvEwnZzJxAfXnyBk8d96uJb+RzML8VaSkeZ5Kw1NubrquBF8wi3Oz7qS2swfTHB3ewYyoQ1gGKROkmjttIOXbWDSg9b54PQCIGMscotO9nENM=
encryptionsalt: v1:AWXWIyh26VY=:v1:Sg6zEq4QvISI5kjW:A7aV13N9kenv/uY9U3IQYM+qiSZTYg==
