/**
 * Generate static compare-pair metadata for all C(n,2) product combinations.
 *
 * Usage:
 *   npm run pipeline -- generate-compare-pairs
 *
 * Outputs: app/src/lib/generated/compare-pairs.ts
 */

import { writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { PRODUCTS } from "../bots.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(__dirname, "../../../app/src/lib/generated/compare-pairs.ts");

export async function generateComparePairs(): Promise<void> {
  // Sort products by ID for deterministic output
  const sorted = [...PRODUCTS].sort((a, b) => a.id.localeCompare(b.id));

  // Generate all C(n,2) pairs with idA < idB (alphabetically)
  const pairs: { idA: string; idB: string; nameA: string; nameB: string; slug: string; title: string; description: string }[] = [];

  for (let i = 0; i < sorted.length; i++) {
    for (let j = i + 1; j < sorted.length; j++) {
      const a = sorted[i];
      const b = sorted[j];
      const slug = `${a.id}-vs-${b.id}`;
      pairs.push({
        idA: a.id,
        idB: b.id,
        nameA: a.name,
        nameB: b.name,
        slug,
        title: `${a.name} vs ${b.name} — AI Code Review Comparison`,
        description: `Compare ${a.name} and ${b.name} AI code review tools side-by-side. See review volume, growth, repos, organizations, and more.`,
      });
    }
  }

  // Generate TypeScript source
  const content = `// Auto-generated by: npm run pipeline -- generate-compare-pairs
// Do not edit manually. Regenerate with the command above.

export type ComparePair = {
  idA: string;
  idB: string;
  nameA: string;
  nameB: string;
  slug: string;
  title: string;
  description: string;
};

export const COMPARE_PAIRS: ComparePair[] = ${JSON.stringify(pairs, null, 2)};

export const PAIR_BY_SLUG = new Map<string, ComparePair>(
  COMPARE_PAIRS.map((p) => [p.slug, p]),
);
`;

  // Ensure output directory exists
  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, content, "utf-8");

  console.log(`✓ Generated ${pairs.length} compare pairs (${sorted.length} products)`);
  console.log(`  Output: ${OUTPUT_PATH}`);
}
